"use client";

import MetricSlider from "./MetricSlider";

interface SecurityConfigProps {
  eventsPerSecond: number;
  onEventsPerSecondChange: (value: number) => void;
}

export default function SecurityConfig({
  eventsPerSecond,
  onEventsPerSecondChange,
}: SecurityConfigProps) {
  return (
    <div className="space-y-6">
      <MetricSlider
        label="Security Events per Second"
        value={eventsPerSecond}
        onChange={onEventsPerSecondChange}
        min={1}
        max={100000}
        step={1}
        formatValue={(v) => `${v.toLocaleString()}/sec`}
      />
      <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
        <p className="text-sm text-blue-800 dark:text-blue-200">
          💡 <strong>Security events per second</strong> represents the rate of security events, alerts, detections, and log entries being generated by your security infrastructure (SIEM, EDR, firewalls, etc.).
        </p>
      </div>
    </div>
  );
}

