"use client";

import MetricSlider from "./MetricSlider";

interface SecurityConfigProps {
  eventsPerSecond: number;
  onEventsPerSecondChange: (value: number) => void;
}

function formatEventsPerSecond(v: number): string {
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(2)}M/sec`;
  if (v >= 1_000) return `${(v / 1_000).toFixed(1)}K/sec`;
  return `${v.toLocaleString()}/sec`;
}

export default function SecurityConfig({
  eventsPerSecond,
  onEventsPerSecondChange,
}: SecurityConfigProps) {
  return (
    <div className="space-y-6">
      <MetricSlider
        label="Security Events per Second"
        value={eventsPerSecond}
        onChange={onEventsPerSecondChange}
        min={1}
        max={1_000_000}
        step={1}
        logarithmic={true}
        formatValue={formatEventsPerSecond}
      />
      <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
        <p className="text-sm text-blue-800 dark:text-blue-200">
          💡 <strong>Security events per second</strong> represents the rate of security events, alerts, detections, and log entries being generated by your security infrastructure (SIEM, EDR, firewalls, etc.).
        </p>
        <div className="border-t border-blue-200 dark:border-blue-700 pt-3 mt-3">
          <p className="text-sm text-blue-800 dark:text-blue-200">
            <strong>Quick reference:</strong> 1K events/sec ≈ 86 GB/day · 10K events/sec ≈ 864 GB/day · 100K events/sec ≈ 8.6 TB/day · 1M events/sec ≈ 86 TB/day
          </p>
        </div>
      </div>
    </div>
  );
}
