"use client";

import MetricSlider from "./MetricSlider";

interface TracingConfigProps {
  spansPerSecond: number;
  onSpansPerSecondChange: (value: number) => void;
}

export default function TracingConfig({
  spansPerSecond,
  onSpansPerSecondChange,
}: TracingConfigProps) {
  return (
    <div className="space-y-6">
      <MetricSlider
        label="Spans per Second"
        value={spansPerSecond}
        onChange={onSpansPerSecondChange}
        min={1}
        max={10000}
        step={1}
        formatValue={(v) => `${v.toLocaleString()}/sec`}
      />
      <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 space-y-3">
        <p className="text-sm text-blue-800 dark:text-blue-200">
          💡 <strong>Spans per second</strong> represents the rate of trace spans being generated by your application. A single request can generate multiple spans across services.
        </p>
        <div className="border-t border-blue-200 dark:border-blue-700 pt-3">
          <p className="text-sm text-blue-800 dark:text-blue-200">
            <strong>Note on Pricing Models:</strong> Different platforms use different pricing models:
          </p>
          <ul className="text-sm text-blue-800 dark:text-blue-200 mt-2 space-y-1 ml-4 list-disc">
            <li><strong>Span-based pricing:</strong> Most platforms charge per million spans ingested</li>
            <li><strong>Trace-based pricing:</strong> Elastic Serverless APM charges per million traces (assumes ~10 spans per trace) with retention costs included</li>
          </ul>
          <p className="text-sm text-blue-800 dark:text-blue-200 mt-2">
            For accurate Elastic APM pricing, the calculator converts spans to traces using an average of 10 spans per trace, matching Elastic's public calculator.
          </p>
        </div>
      </div>
    </div>
  );
}

