"use client";

import MetricSlider from "./MetricSlider";

interface TracingConfigProps {
  spansPerSecond: number;
  onSpansPerSecondChange: (value: number) => void;
}

export default function TracingConfig({
  spansPerSecond,
  onSpansPerSecondChange,
}: TracingConfigProps) {
  return (
    <div className="space-y-6">
      <MetricSlider
        label="Spans per Second"
        value={spansPerSecond}
        onChange={onSpansPerSecondChange}
        min={1}
        max={10000}
        step={1}
        formatValue={(v) => `${v.toLocaleString()}/sec`}
      />
      <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
        <p className="text-sm text-blue-800 dark:text-blue-200">
          💡 <strong>Spans per second</strong> represents the rate of trace spans being generated by your application. A single request can generate multiple spans across services.
        </p>
      </div>
    </div>
  );
}

