"use client";

import MetricSlider from "./MetricSlider";

interface TracingConfigProps {
  spansPerSecond: number;
  onSpansPerSecondChange: (value: number) => void;
}

function formatSpansPerSecond(v: number): string {
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(2)}M/sec`;
  if (v >= 1_000) return `${(v / 1_000).toFixed(1)}K/sec`;
  return `${v.toLocaleString()}/sec`;
}

export default function TracingConfig({
  spansPerSecond,
  onSpansPerSecondChange,
}: TracingConfigProps) {
  return (
    <div className="space-y-6">
      <MetricSlider
        label="Spans per Second"
        value={spansPerSecond}
        onChange={onSpansPerSecondChange}
        min={1}
        max={1_000_000}
        step={1}
        logarithmic={true}
        formatValue={formatSpansPerSecond}
      />
      <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 space-y-3">
        <p className="text-sm text-blue-800 dark:text-blue-200">
          💡 <strong>Spans per second</strong> represents the rate of trace spans being generated by your application. A single request can generate multiple spans across services.
        </p>
        <div className="border-t border-blue-200 dark:border-blue-700 pt-3">
          <p className="text-sm text-blue-800 dark:text-blue-200">
            <strong>Quick reference:</strong> 1K spans/sec = small app · 10K spans/sec = medium scale · 100K spans/sec = high traffic · 1M spans/sec = enterprise scale
          </p>
        </div>
        <div className="border-t border-blue-200 dark:border-blue-700 pt-3">
          <p className="text-sm text-blue-800 dark:text-blue-200">
            <strong>Note on Pricing Models:</strong> Different platforms use different pricing models:
          </p>
          <ul className="text-sm text-blue-800 dark:text-blue-200 mt-2 space-y-1 ml-4 list-disc">
            <li><strong>Span-based pricing:</strong> Most platforms charge per million spans ingested</li>
            <li><strong>Trace-based pricing:</strong> Elastic Serverless and ECH APM charge per million traces (assumes ~10 spans per trace) with retention costs included</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
